require_relative '../modules/file_loader'
require_relative '../modules/repository'
require_relative 'customer'

# Loads and houses customer instances generated by SalesEngine and can use
# repo module methods to search, inspect, create, update, and delete
# instances of Customer.
class CustomerRepository
  include FileLoader
  include Repository
  attr_reader :repository
  def initialize(filepath, parent)
    @repository = []
    @parent = parent
    @unchangeable_keys = %I[id created_at]
    load_attributes(filepath, @repository, Customer)
  end

  def all
    @repository
  end

  def find_by_id(id)
    find_with_id(@repository, id)
  end

  def find_all_by_first_name(first_name)
    find_all_with_instance_string(@repository, first_name, :first_name)
  end

  def find_all_by_last_name(last_name)
    find_all_with_instance_string(@repository, last_name, :last_name)
  end

  def create(attributes)
    create_new_instance(@repository, attributes, Customer)
  end

  def update(id, attributes)
    update_instance(id, attributes, @repository, @unchangeable_keys)
  end

  def delete(id)
    delete_instance(@repository, id)
  end
end
