require_relative '../modules/repository'
require_relative '../modules/file_loader'
require_relative 'invoice_item'

# Loads and houses invoice item instances generated by SalesEngine and can use
# repo module methods to search, inspect, create, update, and delete
# instances of InvoiceItem.
class InvoiceItemRepository
  include FileLoader
  include Repository
  attr_reader :repository
  def initialize(filepath, parent)
    @repository     = []
    @parent            = parent
    @unchangeable_keys = %I[id invoice_id created_at]
    load_attributes(filepath, @repository, InvoiceItem)
  end

  def all
    @repository
  end

  def find_by_id(id)
    find_with_id(@repository, id)
  end

  def find_all_by_item_id(id)
    find_all_with_instance_key(@repository, id, :item_id)
  end

  def find_all_by_invoice_id(id)
    find_all_with_instance_key(@repository, id, :invoice_id)
  end

  def create(attributes)
    create_new_instance(@repository, attributes, InvoiceItem)
  end

  def update(id, attributes)
    update_instance(id, attributes, @repository, @unchangeable_keys)
  end

  def delete(id)
    delete_instance(@repository, id)
  end
end
