require_relative '../modules/repository'
require_relative '../modules/file_loader'
require_relative 'item'

# Loads and houses item instances generated by SalesEngine and can use
# repo module methods to search, inspect, create, update, and delete
# instances of Item.
class ItemRepository
  include FileLoader
  include Repository
  attr_reader :repository
  def initialize(filepath, parent)
    @repository = []
    @parent = parent
    @unchangeable_keys = %I[id item_id created_at]
    load_attributes(filepath, @repository, Item)
  end

  def all
    @repository
  end

  def find_by_id(id)
    find_with_id(@repository, id)
  end

  def find_by_name(name)
    find_by_instance_string(@repository, name, :name)
  end

  def find_all_with_description(description)
    find_all_with_instance_string(@repository, description, :description)
  end

  def find_all_by_price(price)
    find_all_with_instance_key(@repository, price, :unit_price)
  end

  def find_all_by_price_in_range(price_range)
    find_all_instances_in_price_range(@repository, price_range)
  end

  def find_all_by_merchant_id(merchant_id)
    find_all_with_instance_key(@repository, merchant_id, :merchant_id)
  end

  def delete(id)
    delete_instance(@repository, id)
  end

  def create(attributes)
    create_new_instance(@repository, attributes, Item)
  end

  def update(id, attributes)
    update_instance(id, attributes, @repository, @unchangeable_keys)
  end
end
