require_relative '../modules/repository'
require_relative '../modules/file_loader'
require_relative 'transaction'

# # Loads and houses transaction instances generated by SalesEngine and can use
# repo module methods to search, inspect, create, update, and delete
# instances of Transaction.
class TransactionRepository
  include FileLoader
  include Repository
  attr_reader :repository
  def initialize(filepath, parent)
    @repository = []
    @parent = parent
    @unchangeable_keys = %I[id invoice_id created_at]
    load_attributes(filepath, @repository, Transaction)
  end

  def all
    @repository
  end

  def find_by_id(id)
    find_with_id(@repository, id)
  end

  def find_all_by_invoice_id(id)
    find_all_with_instance_key(@repository, id, :invoice_id)
  end

  def find_all_by_credit_card_number(card_number)
    find_all_with_instance_key(@repository, card_number, :credit_card_number)
  end

  def find_all_by_result(result)
    find_all_with_instance_key(@repository, result, :result)
  end

  def delete(id)
    delete_instance(@repository, id)
  end

  def create(attributes)
    create_new_instance(@repository, attributes, Transaction)
  end

  def update(id, attributes)
    update_instance(id, attributes, @repository, @unchangeable_keys)
  end
end
